-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg5+mjTEGL3d2ha5aVVprItET83+grQny/KlBWxr2d9/egCgYIKoZIzj0DAQehRANCAATzbHYQegJbmMEoT34/QsX1Ym7SPGPU9HiaZsCFsF8LZHhgjtKfGOfzEoeg7SGnKXCDIgjnmXwWIfOB454QdjXp
-----END PRIVATE KEY-----